ensure_gem "pry", "~> 0.13.x", "< 0.14"
ensure_gem "pry-byebug"
ensure_gem "pry-doc"
ensure_gem "pry-rails"
ensure_gem "pry-theme"
ensure_gem "dead_end"
#ensure_gem "stackprof"
#ensure_gem "rubyprof"
#ensure_gem "rubyprof-flamegraph"
